import os
import numpy as np
from imblearn.over_sampling import SMOTE
from collections import Counter

# Define paths relative to this script
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PROCESSED_DATA_DIR = os.path.join(BASE_DIR, "processed")

# Input paths (generated by vectorize.py)
X_PATH = os.path.join(PROCESSED_DATA_DIR, "X.npy")
Y_PATH = os.path.join(PROCESSED_DATA_DIR, "y.npy")

# Output paths
X_RESAMPLED_PATH = os.path.join(PROCESSED_DATA_DIR, "X_resampled.npy")
Y_RESAMPLED_PATH = os.path.join(PROCESSED_DATA_DIR, "y_resampled.npy")

def apply_smote_balancing():
    """
    Loads highly dimensional vectorized numerical features (X) and labels (y),
    applies the SMOTE algorithm to generate synthetic minority samples,
    prints the original and new distributions, and saves the balanced arrays.
    """
    if not os.path.exists(X_PATH) or not os.path.exists(Y_PATH):
        print(f"Error: Vectorized arrays not found in {PROCESSED_DATA_DIR}")
        print("Please run 'vectorize.py' first.")
        return

    print("Loading highly dimensional vectorized datasets into memory...")
    # Loading arrays directly
    X = np.load(X_PATH)
    y = np.load(Y_PATH)
    
    # 1. Print class distribution before
    print("\n" + "="*40)
    print("CLASS DISTRIBUTION (BEFORE SMOTE)")
    print("="*40)
    counter_before = Counter(y)
    for cls, count in sorted(counter_before.items()):
        print(f"  - Label {cls}: {count} records")
        
    print("\nInitializing SMOTE Engine...")
    print("Geometrically interpolating synthetic minority data points (this may take a few moments)...")
    
    # 2. Apply SMOTE oversampling
    smote = SMOTE(random_state=42)
    X_resampled, y_resampled = smote.fit_resample(X, y)
    
    # 3. Print class distribution after
    print("\n" + "="*40)
    print("CLASS DISTRIBUTION (AFTER SMOTE)")
    print("="*40)
    counter_after = Counter(y_resampled)
    for cls, count in sorted(counter_after.items()):
        print(f"  - Label {cls}: {count} records")
        
    print(f"\nFinal Synthetic Dataset Size: X={X_resampled.shape}, y={y_resampled.shape}")
        
    # 4. Save the newly synthesized, perfectly balanced dataset
    print("\nSaving balanced, synthetic arrays to disk...")
    os.makedirs(PROCESSED_DATA_DIR, exist_ok=True)
    
    np.save(X_RESAMPLED_PATH, X_resampled)
    np.save(Y_RESAMPLED_PATH, y_resampled)
    
    print("Done! Artifacts saved successfully:")
    print(f"  - {X_RESAMPLED_PATH}")
    print(f"  - {Y_RESAMPLED_PATH}")

if __name__ == "__main__":
    apply_smote_balancing()
