"""add_metadata_to_attachments

Revision ID: 4638f7ca9728
Revises: f23554c872aa
Create Date: 2026-06-20 03:33:53.150821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4638f7ca9728'
down_revision: Union[str, None] = 'f23554c872aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('attachments', sa.Column('checksum', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'checksum')
    op.drop_column('attachments', 'mime_type')
    # ### end Alembic commands ###
